pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,7 +57,7 @@ jobs:
           echo "Deployment not yet performed. Proceeding with deployment."
           echo "deployed" > deployment-flag.txt
           # Run the deployment
-          mysql -h ${{ secrets.RDS_ENDPOINT }} -u ${{ secrets.RDS_USERNAME }} -p${{ secrets.RDS_PASSWORD }} ${{ secrets.DATABASE_NAME }} < db-load-script.sql
+          mysql -h ${{ secrets.RDS_ENDPOINT }} -u ${{ secrets.RDS_USERNAME }} -p${{ secrets.RDS_PASSWORD }} ${{ secrets.DATABASE_NAME }} < db-load-script.sql || echo "Error during deployment"
 
       - name: Skip Deployment
         if: steps.cache.outputs.cache-hit == 'true'
